import React,{useState} from "react";
import { View, Text, ScrollView, RefreshControl } from "react-native";


export default function(){

  const [atulizando,setAtualizando] = useState(false)

  const aoAtualizando = () => {setAtualizando(true); setTimeout(() => {setAtualizando(false)},3000)
  }

  return(
  <View style={{flex:1}}>
   <ScrollView  refreshControl={<RefreshControl onRefresh={aoAtualizando}  refreshing={atulizando} />} o    style={{backgroundColor:'#333', padding:15}}  >
    <Text style={{color:'white'}}>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt erat eu ex imperdiet, vel venenatis enim accumsan. Aenean at magna ante. Sed maximus turpis eu fermentum imperdiet. Ut ultricies lacus feugiat erat congue, sit amet pulvinar justo posuere. Cras tempus bibendum enim, a ultricies neque blandit sit amet. Sed placerat egestas dolor at scelerisque. Fusce justo ligula, congue at elit nec, vulputate tincidunt libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet sollicitudin euismod. Ut consequat purus ut condimentum pulvinar.

Donec non vestibulum est, ut suscipit ante. Mauris tristique nunc nec elit tristique aliquet. Pellentesque justo nunc, egestas ornare mauris eget, vestibulum mattis nulla. Donec a accumsan nisl, sit amet mattis nisl. Ut vitae est volutpat orci volutpat egestas et quis metus. Cras pharetra maximus metus a finibus. Proin ut elit metus. Vivamus fermentum sapien eu diam porta, id vulputate elit convallis. Vivamus mattis condimentum magna, id tristique ex pulvinar ac. Curabitur sagittis elementum magna, eget semper enim maximus sed. Morbi eu nulla vitae felis hendrerit pharetra. Nullam sit amet leo eu mauris elementum volutpat et sit amet eros. Ut eget tortor quis sem aliquam fringilla id et nisi. Mauris risus lectus, luctus in elit id, blandit dictum mauris. Praesent sollicitudin vitae mi non fringilla.

Vivamus feugiat felis vel neque convallis, ac tempus erat venenatis. Vestibulum semper, magna nec vulputate ullamcorper, nibh eros placerat risus, vitae congue arcu risus sed nisl. Quisque scelerisque porttitor magna, in lacinia felis rhoncus vel. Curabitur vehicula aliquet orci id eleifend. Proin aliquet lorem sit amet purus accumsan congue. Vestibulum a egestas ipsum. Praesent eu augue porta, tincidunt quam nec, posuere risus. Sed quis egestas velit. Quisque id risus tempor, accumsan ipsum sit amet, consectetur felis. Cras non ex sodales, facilisis lectus nec, pretium arcu. Quisque euismod eros non dui elementum condimentum. Vivamus sem mi, sagittis id congue eu, porttitor in eros.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt erat eu ex imperdiet, vel venenatis enim accumsan. Aenean at magna ante. Sed maximus turpis eu fermentum imperdiet. Ut ultricies lacus feugiat erat congue, sit amet pulvinar justo posuere. Cras tempus bibendum enim, a ultricies neque blandit sit amet. Sed placerat egestas dolor at scelerisque. Fusce justo ligula, congue at elit nec, vulputate tincidunt libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet sollicitudin euismod. Ut consequat purus ut condimentum pulvinar.

Donec non vestibulum est, ut suscipit ante. Mauris tristique nunc nec elit tristique aliquet. Pellentesque justo nunc, egestas ornare mauris eget, vestibulum mattis nulla. Donec a accumsan nisl, sit amet mattis nisl. Ut vitae est volutpat orci volutpat egestas et quis metus. Cras pharetra maximus metus a finibus. Proin ut elit metus. Vivamus fermentum sapien eu diam porta, id vulputate elit convallis. Vivamus mattis condimentum magna, id tristique ex pulvinar ac. Curabitur sagittis elementum magna, eget semper enim maximus sed. Morbi eu nulla vitae felis hendrerit pharetra. Nullam sit amet leo eu mauris elementum volutpat et sit amet eros. Ut eget tortor quis sem aliquam fringilla id et nisi. Mauris risus lectus, luctus in elit id, blandit dictum mauris. Praesent sollicitudin vitae mi non fringilla.

Vivamus feugiat felis vel neque convallis, ac tempus erat venenatis. Vestibulum semper, magna nec vulputate ullamcorper, nibh eros placerat risus, vitae congue arcu risus sed nisl. Quisque scelerisque porttitor magna, in lacinia felis rhoncus vel. Curabitur vehicula aliquet orci id eleifend. Proin aliquet lorem sit amet purus accumsan congue. Vestibulum a egestas ipsum. Praesent eu augue porta, tincidunt quam nec, posuere risus. Sed quis egestas velit. Quisque id risus tempor, accumsan ipsum sit amet, consectetur felis. Cras non ex sodales, facilisis lectus nec, pretium arcu. Quisque euismod eros non dui elementum condimentum. Vivamus sem mi, sagittis id congue eu, porttitor in eros.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt erat eu ex imperdiet, vel venenatis enim accumsan. Aenean at magna ante. Sed maximus turpis eu fermentum imperdiet. Ut ultricies lacus feugiat erat congue, sit amet pulvinar justo posuere. Cras tempus bibendum enim, a ultricies neque blandit sit amet. Sed placerat egestas dolor at scelerisque. Fusce justo ligula, congue at elit nec, vulputate tincidunt libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet sollicitudin euismod. Ut consequat purus ut condimentum pulvinar.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt erat eu ex imperdiet, vel venenatis enim accumsan. Aenean at magna ante. Sed maximus turpis eu fermentum imperdiet. Ut ultricies lacus feugiat erat congue, sit amet pulvinar justo posuere. Cras tempus bibendum enim, a ultricies neque blandit sit amet. Sed placerat egestas dolor at scelerisque. Fusce justo ligula, congue at elit nec, vulputate tincidunt libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet sollicitudin euismod. Ut consequat purus ut condimentum pulvinar.

Donec non vestibulum est, ut suscipit ante. Mauris tristique nunc nec elit tristique aliquet. Pellentesque justo nunc, egestas ornare mauris eget, vestibulum mattis nulla. Donec a accumsan nisl, sit amet mattis nisl. Ut vitae est volutpat orci volutpat egestas et quis metus. Cras pharetra maximus metus a finibus. Proin ut elit metus. Vivamus fermentum sapien eu diam porta, id vulputate elit convallis. Vivamus mattis condimentum magna, id tristique ex pulvinar ac. Curabitur sagittis elementum magna, eget semper enim maximus sed. Morbi eu nulla vitae felis hendrerit pharetra. Nullam sit amet leo eu mauris elementum volutpat et sit amet eros. Ut eget tortor quis sem aliquam fringilla id et nisi. Mauris risus lectus, luctus in elit id, blandit dictum mauris. Praesent sollicitudin vitae mi non fringilla.

Vivamus feugiat felis vel neque convallis, ac tempus erat venenatis. Vestibulum semper, magna nec vulputate ullamcorper, nibh eros placerat risus, vitae congue arcu risus sed nisl. Quisque scelerisque porttitor magna, in lacinia felis rhoncus vel. Curabitur vehicula aliquet orci id eleifend. Proin aliquet lorem sit amet purus accumsan congue. Vestibulum a egestas ipsum. Praesent eu augue porta, tincidunt quam nec, posuere risus. Sed quis egestas velit. Quisque id risus tempor, accumsan ipsum sit amet, consectetur felis. Cras non ex sodales, facilisis lectus nec, pretium arcu. Quisque euismod eros non dui elementum condimentum. Vivamus sem mi, sagittis id congue eu, porttitor in eros.

Donec non vestibulum est, ut suscipit ante. Mauris tristique nunc nec elit tristique aliquet. Pellentesque justo nunc, egestas ornare mauris eget, vestibulum mattis nulla. Donec a accumsan nisl, sit amet mattis nisl. Ut vitae est volutpat orci volutpat egestas et quis metus. Cras pharetra maximus metus a finibus. Proin ut elit metus. Vivamus fermentum sapien eu diam porta, id vulputate elit convallis. Vivamus mattis condimentum magna, id tristique ex pulvinar ac. Curabitur sagittis elementum magna, eget semper enim maximus sed. Morbi eu nulla vitae felis hendrerit pharetra. Nullam sit amet leo eu mauris elementum volutpat et sit amet eros. Ut eget tortor quis sem aliquam fringilla id et nisi. Mauris risus lectus, luctus in elit id, blandit dictum mauris. Praesent sollicitudin vitae mi non fringilla.

Vivamus feugiat felis vel neque convallis, ac tempus erat venenatis. Vestibulum semper, magna nec vulputate ullamcorper, nibh eros placerat risus, vitae congue arcu risus sed nisl. Quisque scelerisque porttitor magna, in lacinia felis rhoncus vel. Curabitur vehicula aliquet orci id eleifend. Proin aliquet lorem sit amet purus accumsan congue. Vestibulum a egestas ipsum. Praesent eu augue porta, tincidunt quam nec, posuere risus. Sed quis egestas velit. Quisque id risus tempor, accumsan ipsum sit amet, consectetur felis. Cras non ex sodales, facilisis lectus nec, pretium arcu. Quisque euismod eros non dui elementum condimentum. Vivamus sem mi, sagittis id congue eu, porttitor in eros.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt erat eu ex imperdiet, vel venenatis enim accumsan. Aenean at magna ante. Sed maximus turpis eu fermentum imperdiet. Ut ultricies lacus feugiat erat congue, sit amet pulvinar justo posuere. Cras tempus bibendum enim, a ultricies neque blandit sit amet. Sed placerat egestas dolor at scelerisque. Fusce justo ligula, congue at elit nec, vulputate tincidunt libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet sollicitudin euismod. Ut consequat purus ut condimentum pulvinar.

Donec non vestibulum est, ut suscipit ante. Mauris tristique nunc nec elit tristique aliquet. Pellentesque justo nunc, egestas ornare mauris eget, vestibulum mattis nulla. Donec a accumsan nisl, sit amet mattis nisl. Ut vitae est volutpat orci volutpat egestas et quis metus. Cras pharetra maximus metus a finibus. Proin ut elit metus. Vivamus fermentum sapien eu diam porta, id vulputate elit convallis. Vivamus mattis condimentum magna, id tristique ex pulvinar ac. Curabitur sagittis elementum magna, eget semper enim maximus sed. Morbi eu nulla vitae felis hendrerit pharetra. Nullam sit amet leo eu mauris elementum volutpat et sit amet eros. Ut eget tortor quis sem aliquam fringilla id et nisi. Mauris risus lectus, luctus in elit id, blandit dictum mauris. Praesent sollicitudin vitae mi non fringilla.

Vivamus feugiat felis vel neque convallis, ac tempus erat venenatis. Vestibulum semper, magna nec vulputate ullamcorper, nibh eros placerat risus, vitae congue arcu risus sed nisl. Quisque scelerisque porttitor magna, in lacinia felis rhoncus vel. Curabitur vehicula aliquet orci id eleifend. Proin aliquet lorem sit amet purus accumsan congue. Vestibulum a egestas ipsum. Praesent eu augue porta, tincidunt quam nec, posuere risus. Sed quis egestas velit. Quisque id risus tempor, accumsan ipsum sit amet, consectetur felis. Cras non ex sodales, facilisis lectus nec, pretium arcu. Quisque euismod eros non dui elementum condimentum. Vivamus sem mi, sagittis id congue eu, porttitor in eros.

Morbi et nunc non nisl ultricies sollicitudin. Phasellus venenatis, lectus quis facilisis cursus, eros risus faucibus lectus, sed eleifend orci sapien sit amet felis. Maecenas porttitor mi a ligula hendrerit luctus. Ut quis sem malesuada, sollicitudin orci at, fermentum risus. Pellentesque scelerisque risus mauris, eu tincidunt erat tempus nec. Integer vel ullamcorper elit. Aenean pellentesque, velit vitae interdum imperdiet, risus felis tincidunt lorem, ac aliquet orci lorem ac nisi. Curabitur eu aliquet sapien. Ut sed commodo lacus, a malesuada justo. Proin venenatis turpis turpis, id rutrum nulla egestas non. Donec quis purus in nisi finibus molestie.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque mattis velit at lacus feugiat scelerisque. Phasellus placerat leo est, ac posuere nisi pulvinar non. Duis euismod mattis nunc, at ultricies dui convallis tempus. Proin efficitur sit amet massa vitae feugiat. Sed semper molestie odio in mollis. Ut aliquet, nibh at pellentesque auctor, ante massa tempor elit, nec sollicitudin ex purus vitae metus. Etiam et ligula est. Phasellus consectetur lacinia lectus, vel pulvinar lectus semper ac. Aenean semper ipsum sit amet lorem mollis, ut malesuada lectus commodo. Nunc volutpat eleifend malesuada. Fusce ultricies, mauris in posuere gravida, eros odio dictum mi, a lobortis ex nulla eget diam.

</Text>
   </ScrollView>
  </View>
  )
}